/* Question bank distilled from the supplied 2025–2026 International Banking exam notes. */
window.QUESTION_BANK = [
  {id:"intro-01",category:"Banking foundations",q:"Which activity is most characteristic of a commercial bank serving households and SMEs?",o:["Taking deposits and making loans","Underwriting only sovereign bonds","Operating a stock exchange","Issuing corporate credit ratings"],a:0,e:"Commercial banks provide payment and savings products and transform deposits into lending for households and businesses."},
  {id:"intro-02",category:"Banking foundations",q:"Which service is most closely associated with investment banking?",o:["Securities underwriting","Retail current accounts","Deposit insurance","Cash withdrawals at branches"],a:0,e:"Investment banks commonly underwrite debt and equity issues and provide advisory, valuation, trading and risk-management services."},
  {id:"intro-03",category:"Banking foundations",q:"A universal bank is best described as a bank that…",o:["Combines commercial and investment banking activities","Accepts deposits but cannot lend","Operates in only one country","Is owned by a central bank"],a:0,e:"Universal banking combines a broad commercial-banking franchise with investment-banking and other financial services."},
  {id:"intro-04",category:"Banking foundations",q:"What is the core economic role of maturity transformation?",o:["Funding longer-term assets with shorter-term liabilities","Replacing all loans with securities","Matching every asset with equity","Eliminating credit risk through diversification"],a:0,e:"Banks typically fund relatively illiquid, long-term loans with shorter-term and more liquid deposits, creating liquidity and maturity risk."},
  {id:"intro-05",category:"Banking foundations",q:"A bank's net interest income equals…",o:["Interest income minus interest expense","Fee income minus operating expenses","Revenue minus loan-loss provisions","Assets minus liabilities"],a:0,e:"Net interest income is the spread-based income from interest-earning assets after the cost of interest-bearing liabilities."},
  {id:"intro-06",category:"Banking foundations",q:"Which item is normally classified as non-interest income?",o:["Account service fees","Interest on mortgages","Coupon income on bonds","Interest paid on deposits"],a:0,e:"Fees, service charges and other service revenues are non-interest income."},

  {id:"fs-01",category:"Financial statements & ratios",q:"Which statement presents a bank's assets, liabilities and shareholders' equity at a point in time?",o:["Balance sheet","Income statement","Cash-flow statement","Statement of comprehensive income only"],a:0,e:"The balance sheet is the point-in-time statement of financial position."},
  {id:"fs-02",category:"Financial statements & ratios",q:"Return on equity (ROE) is generally calculated as…",o:["Net income divided by average equity","Net income divided by total deposits","Operating income divided by RWAs","Equity divided by total assets"],a:0,e:"ROE measures the earnings produced for shareholders relative to their average book equity."},
  {id:"fs-03",category:"Financial statements & ratios",q:"A lower cost-income ratio generally indicates…",o:["Greater operating efficiency","Higher credit risk","Lower capitalization","More wholesale funding"],a:0,e:"The ratio compares operating costs with operating income; a lower figure generally means better cost efficiency."},
  {id:"fs-04",category:"Financial statements & ratios",q:"Risk-weighted asset density is commonly measured as…",o:["RWAs divided by total assets","CET1 divided by RWAs","Net income divided by RWAs","Loans divided by deposits"],a:0,e:"RWA density shows how risk-intensive the asset base is by comparing risk-weighted assets with total assets."},
  {id:"fs-05",category:"Financial statements & ratios",q:"Which valuation relationship is most directly relevant to a bank's price-to-tangible-book multiple?",o:["Expected ROE relative to the cost of equity","Revenue relative to deposits","LCR relative to NSFR","Loan growth relative to GDP"],a:0,e:"Sustainable ROE above the cost of equity supports a price above tangible book value; the opposite tends to depress it."},
  {id:"fs-06",category:"Financial statements & ratios",q:"Tangible shareholders' equity excludes…",o:["Goodwill and other intangible assets","Retained earnings","Common shares","Cash reserves"],a:0,e:"Tangible equity removes goodwill and other intangibles from book equity to focus on loss-absorbing tangible value."},

  {id:"irr-01",category:"Interest-rate risk",q:"In repricing GAP analysis, periodic GAP equals…",o:["Rate-sensitive assets minus rate-sensitive liabilities","Total assets minus total liabilities","Fixed-rate assets minus equity","Interest income minus provisions"],a:0,e:"GAP compares assets and liabilities that mature or reprice within the selected time bucket."},
  {id:"irr-02",category:"Interest-rate risk",q:"If a bank has a positive repricing GAP and market rates rise, its net interest income will generally…",o:["Increase","Decrease","Remain unchanged by definition","Become equal to EVE"],a:0,e:"With more assets than liabilities repricing upward, asset yield changes tend to exceed funding-cost changes."},
  {id:"irr-03",category:"Interest-rate risk",q:"A negative repricing GAP means the bank has…",o:["More rate-sensitive liabilities than rate-sensitive assets","More equity than liabilities","No exposure to changing rates","Only fixed-rate funding"],a:0,e:"A negative GAP exposes net interest income to falling when rates rise, all else equal."},
  {id:"irr-04",category:"Interest-rate risk",q:"Which is a key limitation of simple static GAP analysis?",o:["It assumes a parallel rate shift and can ignore embedded options","It requires market values for every cash flow","It measures only operational risk","It cannot use maturity buckets"],a:0,e:"Static GAP makes simplifying assumptions about rate changes and often ignores options, basis effects and changes in economic value."},
  {id:"irr-05",category:"Interest-rate risk",q:"Duration GAP analysis primarily targets changes in…",o:["Economic value of equity","Fee income","Loan-loss provisions","Operational expenses"],a:0,e:"Duration measures the sensitivity of asset and liability values, allowing the bank to estimate the change in EVE."},
  {id:"irr-06",category:"Interest-rate risk",q:"An interest-rate swap can help a bank…",o:["Alter the fixed/floating profile without selling the underlying assets","Eliminate all credit losses","Increase deposit insurance","Convert CET1 into Tier 2"],a:0,e:"Swaps change the bank's cash-flow sensitivity and can hedge large periodic GAPs without changing the underlying balance sheet."},

  {id:"liq-01",category:"Liquidity & funding",q:"Funding liquidity risk is the risk that a bank…",o:["Cannot obtain funds to meet payment obligations","Cannot estimate a borrower's probability of default","Loses money from an equity-price fall","Experiences an internal systems failure"],a:0,e:"Funding liquidity risk concerns the ability to raise cash or funding when obligations fall due."},
  {id:"liq-02",category:"Liquidity & funding",q:"The Basel III Liquidity Coverage Ratio requires sufficient HQLA to cover…",o:["30-day stressed net cash outflows","One year of operating expenses","All deposits immediately","Expected annual credit losses"],a:0,e:"LCR = high-quality liquid assets divided by stressed net cash outflows over the next 30 calendar days."},
  {id:"liq-03",category:"Liquidity & funding",q:"The Net Stable Funding Ratio uses which horizon?",o:["One year","Thirty days","Five years","One business day"],a:0,e:"NSFR promotes a stable funding structure over a one-year horizon by comparing available with required stable funding."},
  {id:"liq-04",category:"Liquidity & funding",q:"A very high loans-to-deposits ratio can indicate…",o:["Greater reliance on non-deposit funding","Excess CET1 capital","No liquidity risk","A lower cost-income ratio"],a:0,e:"When loans substantially exceed deposits, the bank must rely more heavily on wholesale or other funding sources."},
  {id:"liq-05",category:"Liquidity & funding",q:"Which asset is most likely to qualify as high-quality liquid assets in an LCR calculation?",o:["A readily marketable high-quality sovereign bond","An overdue unsecured loan","Goodwill","A branch building"],a:0,e:"HQLA must be readily monetizable under stress; high-quality sovereign securities are a central example."},
  {id:"liq-06",category:"Liquidity & funding",q:"A classic bank run can become self-reinforcing primarily because banks…",o:["Hold illiquid assets against withdrawable liabilities","Value every loan daily","Finance only with equity","Have no payment obligations"],a:0,e:"Banks cannot immediately liquidate long-term assets without losses, while depositors may demand repayment quickly."},

  {id:"sec-01",category:"Securitisation",q:"In a true-sale securitisation, the originator transfers a pool of assets to…",o:["A special-purpose vehicle","The deposit guarantee scheme","The central bank's supervisory arm","A rating agency"],a:0,e:"The SPV purchases the pool and funds it by issuing asset-backed securities."},
  {id:"sec-02",category:"Securitisation",q:"The cash flows used to pay ABS investors primarily come from…",o:["The underlying asset pool","The originator's common equity","Deposit insurance premiums","Supervisory fees"],a:0,e:"Principal and interest collected from the securitized receivables service the securities."},
  {id:"sec-03",category:"Securitisation",q:"Which tranche normally absorbs the first losses?",o:["Junior/equity tranche","Senior tranche","Covered-bond tranche","Government tranche"],a:0,e:"Subordination creates credit enhancement: the junior tranche absorbs losses before mezzanine and senior tranches."},
  {id:"sec-04",category:"Securitisation",q:"Compared with the junior tranche, the senior ABS tranche normally has…",o:["Higher priority and lower expected yield","Lower priority and higher expected yield","The same risk by construction","No claim on pool cash flows"],a:0,e:"Seniority reduces expected loss and therefore generally carries a lower return."},
  {id:"sec-05",category:"Securitisation",q:"What distinguishes synthetic securitisation from a true sale?",o:["Credit risk is transferred without selling the underlying assets","No tranching is permitted","Only mortgages may be used","The SPV must become a bank"],a:0,e:"Synthetic structures transfer credit risk, often through guarantees or credit derivatives, while the assets remain on the originator's balance sheet."},
  {id:"sec-06",category:"Securitisation",q:"Which feature makes a pool especially suitable for securitisation?",o:["Predictable cash flows across many reasonably homogeneous exposures","A single asset with entirely uncertain cash flows","Assets that cannot legally be transferred","Perfect correlation across all borrowers"],a:0,e:"Predictability, standardization and diversification make pool performance more measurable and securities easier to structure."},

  {id:"credit-01",category:"Credit risk & NPLs",q:"Which non-performing category generally carries the highest borrower distress?",o:["Bad loans","Performing exposures","Stage 1 loans","Cash equivalents"],a:0,e:"Bad loans are exposures to insolvent or severely distressed debtors and are the highest-risk NPL category."},
  {id:"credit-02",category:"Credit risk & NPLs",q:"The gross NPE ratio is generally gross non-performing exposures divided by…",o:["Gross customer loans or total relevant exposures","Shareholders' equity","Net interest income","Operating costs"],a:0,e:"The ratio measures the share of the loan/exposure book that is non-performing before provisions."},
  {id:"credit-03",category:"Credit risk & NPLs",q:"A coverage ratio measures…",o:["Loan-loss provisions relative to the corresponding impaired exposures","CET1 relative to total assets","Deposits relative to loans","HQLA relative to RWAs"],a:0,e:"Coverage shows how much of the problem exposure is already offset by accumulated provisions."},
  {id:"credit-04",category:"Credit risk & NPLs",q:"The cost of risk is commonly expressed in basis points by relating loan-loss provisions to…",o:["The loan book, typically average or gross loans","Total deposits","Market capitalization","Operating income only"],a:0,e:"Cost of risk converts the period's credit-loss charge into a rate on the lending exposure."},
  {id:"credit-05",category:"Credit risk & NPLs",q:"A net NPE ratio differs from a gross NPE ratio because net NPEs…",o:["Deduct accumulated provisions","Exclude all defaulted borrowers","Include only cash","Add goodwill"],a:0,e:"Net non-performing exposures are gross NPEs after the corresponding impairment allowances."},
  {id:"credit-06",category:"Credit risk & NPLs",q:"The Texas ratio compares problem assets with…",o:["Tangible common equity plus loan-loss reserves","High-quality liquid assets","Net interest income","Risk-weighted assets only"],a:0,e:"The Texas ratio gauges whether tangible capital and reserves can absorb non-performing assets."},

  {id:"basel-01",category:"Basel capital",q:"Under Basel III, the minimum CET1 ratio before buffers is…",o:["4.5% of RWAs","3% of total assets","6% of RWAs","8% of total assets"],a:0,e:"The Basel III minimum is 4.5% CET1; additional buffers sit above this floor."},
  {id:"basel-02",category:"Basel capital",q:"The minimum Tier 1 capital ratio before buffers is…",o:["6% of RWAs","4.5% of RWAs","8% of RWAs","3% of RWAs"],a:0,e:"Tier 1 comprises CET1 plus Additional Tier 1 and has a 6% minimum under Basel III."},
  {id:"basel-03",category:"Basel capital",q:"The minimum total regulatory capital ratio before buffers is…",o:["8% of RWAs","10.5% of RWAs","6% of total assets","3% of RWAs"],a:0,e:"Total capital, including Tier 2, must be at least 8% of risk-weighted assets before buffers."},
  {id:"basel-04",category:"Basel capital",q:"The capital conservation buffer is normally…",o:["2.5% of RWAs, met with CET1","3% of total assets, met with Tier 2","8% of deposits, met with cash","1% of loans, met with provisions"],a:0,e:"The Basel III conservation buffer is 2.5% of RWAs and must be composed of CET1."},
  {id:"basel-05",category:"Basel capital",q:"Which statement about Additional Tier 1 instruments is correct?",o:["They are perpetual and coupons are discretionary","They rank senior to deposits","They always mature within five years","Missing a coupon automatically causes insolvency"],a:0,e:"AT1 is deeply subordinated, perpetual, can absorb losses, and has discretionary coupons."},
  {id:"basel-06",category:"Basel capital",q:"The Basel III leverage ratio is designed as…",o:["A non-risk-weighted backstop","A replacement for the LCR","A measure of loan profitability","A credit-rating scale"],a:0,e:"The leverage ratio constrains overall exposure regardless of modeled risk weights; the minimum benchmark is 3%."},

  {id:"sup-01",category:"Supervision & Banking Union",q:"Which Basel II pillar covers minimum capital requirements?",o:["Pillar 1","Pillar 2","Pillar 3","Pillar 4"],a:0,e:"Pillar 1 sets minimum capital requirements for credit, market and operational risks."},
  {id:"sup-02",category:"Supervision & Banking Union",q:"Which Basel II pillar established the supervisory review process?",o:["Pillar 2","Pillar 1","Pillar 3","The conservation buffer"],a:0,e:"Pillar 2 gives supervisors a structured process to assess risks, governance and capital adequacy beyond Pillar 1."},
  {id:"sup-03",category:"Supervision & Banking Union",q:"Pillar 3 of Basel II is primarily intended to strengthen…",o:["Market discipline through disclosure","Deposit insurance","Monetary policy transmission","Bank resolution funding"],a:0,e:"Public risk and capital disclosures allow market participants to exert discipline."},
  {id:"sup-04",category:"Supervision & Banking Union",q:"Within the Single Supervisory Mechanism, significant institutions are directly supervised by…",o:["The European Central Bank","The Single Resolution Board","The European Commission alone","National deposit guarantee schemes"],a:0,e:"The ECB directly supervises significant euro-area banks, working with national competent authorities."},
  {id:"sup-05",category:"Supervision & Banking Union",q:"Which area is assessed in the SREP?",o:["Business model, governance, capital and liquidity risks","Only the bank's share price","Only monetary-policy eligibility","Only deposit insurance fees"],a:0,e:"SREP combines business-model analysis, governance and risk management, risks to capital, and liquidity/funding risks."},
  {id:"sup-06",category:"Supervision & Banking Union",q:"Who normally supervises less significant institutions day to day within the SSM?",o:["National competent authorities under ECB oversight","The IMF","Rating agencies","The Single Resolution Fund"],a:0,e:"National supervisors directly oversee less significant banks, while the ECB retains oversight and consistency powers."},

  {id:"res-01",category:"Resolution",q:"The Single Resolution Mechanism is primarily responsible for…",o:["Orderly resolution of failing banks in participating states","Setting monetary policy rates","Approving all retail loans","Publishing credit ratings"],a:0,e:"The SRM provides centralized resolution decision-making and funding arrangements for Banking Union banks."},
  {id:"res-02",category:"Resolution",q:"A bank is considered failing or likely to fail when, among other conditions, it…",o:["Is unable to pay debts as they fall due","Reports one quarter of lower profits","Changes its dividend policy","Closes a branch"],a:0,e:"Actual or imminent balance-sheet insolvency, liquidity insolvency, authorization failure or need for extraordinary public support may trigger FOLTF."},
  {id:"res-03",category:"Resolution",q:"Which resolution tool transfers shares or assets to a private purchaser?",o:["Sale of business","Asset separation only","SREP","LCR"],a:0,e:"The sale-of-business tool allows transfer to a private buyer without ordinary shareholder approval procedures."},
  {id:"res-04",category:"Resolution",q:"The bail-in tool works mainly by…",o:["Writing down or converting eligible liabilities into equity","Paying every creditor with public funds","Selling only HQLA","Increasing deposit rates"],a:0,e:"Bail-in allocates losses and recapitalization costs to shareholders and eligible creditors rather than taxpayers."},
  {id:"res-05",category:"Resolution",q:"The asset-separation tool transfers selected assets to…",o:["An asset-management vehicle","The monetary-policy portfolio","A rating agency","The deposit guarantee fund permanently"],a:0,e:"An asset-management vehicle can isolate and manage difficult assets while the viable business continues."},
  {id:"res-06",category:"Resolution",q:"MREL is intended to ensure that banks hold enough…",o:["Own funds and eligible liabilities for loss absorption and recapitalization","Cash to cover every deposit at once","Government bonds for monetary policy","Loan-loss provisions for all performing loans"],a:0,e:"MREL supports credible resolution by pre-positioning instruments that can absorb losses and recapitalize the bank."}
];

// Rotate answer positions so the correct choice is evenly distributed across A–D.
window.QUESTION_BANK.forEach((item, index) => {
  item.subject = item.subject || "intl-banking";
  const shift = index % item.o.length;
  item.o = item.o.slice(shift).concat(item.o.slice(0, shift));
  item.a = (item.a - shift + item.o.length) % item.o.length;
});
