/* Strategy question bank built from the supplied Williams sessions, compact theory decks,
   Crocs answered exam, and course cases. */
(() => {
  const questions = [
    {id:"str-found-01",subject:"strategy",category:"Strategy foundations",q:"Which statement best distinguishes business strategy from corporate strategy?",o:["Business strategy asks how to compete; corporate strategy asks where to compete","Business strategy sets accounting rules; corporate strategy sets prices","Business strategy concerns only startups; corporate strategy concerns only listed firms","Business strategy is short term; corporate strategy is always long term"],a:0,e:"Business strategy concerns competitive advantage within a market. Corporate strategy concerns product, vertical, and geographic scope across markets."},
    {id:"str-found-02",subject:"strategy",category:"Strategy foundations",q:"What are the three elements of the good-strategy kernel?",o:["Diagnosis, guiding policy, and coherent actions","Mission, vision, and quarterly targets","Market share, revenue, and profit","Forecast, budget, and control"],a:0,e:"A good strategy diagnoses the central challenge, selects a guiding policy, and commits to mutually reinforcing actions."},
    {id:"str-found-03",subject:"strategy",category:"Strategy foundations",q:"Why is a growth target not, by itself, a strategy?",o:["It does not explain the choices, resources, and actions that will create and capture value","Growth can never create shareholder value","Targets apply only to operational plans","A strategy must avoid all numerical objectives"],a:0,e:"Goals state desired ends. Strategy explains the causal logic and trade-offs through which the firm will reach them."},
    {id:"str-found-04",subject:"strategy",category:"Strategy foundations",q:"If willingness to pay is 140, price is 100, cost is 65, and willingness to sell is 45, how much value does the firm capture?",o:["35","40","75","95"],a:0,e:"Firm value capture is price minus cost: 100 - 65 = 35. Total value created is WTP minus WTS: 140 - 45 = 95."},
    {id:"str-found-05",subject:"strategy",category:"Strategy foundations",q:"A resource improves product reliability. Which causal chain most convincingly explains competitive advantage?",o:["Reliability raises customer WTP, supports value capture, and remains difficult for rivals to replicate","Reliability is a strength, therefore profits must rise","Reliability increases market size regardless of price or cost","Reliability proves the industry is attractive"],a:0,e:"Strong strategy analysis links a resource to WTP or cost, then to capture and durability rather than stopping at description."},
    {id:"str-found-06",subject:"strategy",category:"Strategy foundations",q:"What does strategy as fit emphasize?",o:["Alignment between the firm's goals, resources, systems, and its competitive environment","Maximizing the number of independent initiatives","Following the market leader's activity system","Avoiding trade-offs so every customer segment is served"],a:0,e:"Fit requires the internal activity system and capabilities to reinforce a position that matches external conditions."},
    {id:"str-found-07",subject:"strategy",category:"Strategy foundations",q:"Which statement about profit is analytically strongest?",o:["Profit is evidence of performance, but the strategy answer must explain its causal source","Profit is the definition of strategy","Profit proves that every resource is valuable","Profit always demonstrates a sustainable advantage"],a:0,e:"Performance is an outcome. Analysis must identify the position, resource, activity, or market mechanism that produced it and test durability."},
    {id:"str-found-08",subject:"strategy",category:"Strategy foundations",q:"Why do coherent actions matter in a good strategy?",o:["They reinforce the guiding policy and concentrate scarce resources on the diagnosed challenge","They allow every department to pursue unrelated priorities","They eliminate the need for implementation","They make environmental analysis unnecessary"],a:0,e:"Coherence turns a policy into an activity system. Scattered actions dilute resources and often create internal contradictions."},

    {id:"str-ind-01",subject:"strategy",category:"Industry analysis",q:"Before applying the Five Forces, what should an analyst do first?",o:["Define the industry's product, geographic, and time scope","Calculate the focal firm's ROE","Identify the CEO's leadership style","Choose a diversification mode"],a:0,e:"Force ratings depend on the arena being analyzed. An overbroad or narrow definition can reverse the conclusion."},
    {id:"str-ind-02",subject:"strategy",category:"Industry analysis",q:"A high Five Forces rating means that the force is...",o:["Putting strong pressure on the focal industry's profitability","Creating high profits for every incumbent","Making entry attractive","Increasing total value created for customers"],a:0,e:"A high force is unfavorable to industry capture: it pressures prices, costs, volumes, or the ability to retain surplus."},
    {id:"str-ind-03",subject:"strategy",category:"Industry analysis",q:"Which rivalry pattern is usually most damaging to industry profitability?",o:["Repeated price cutting among firms with excess capacity","Advertising competition among differentiated brands","Innovation in a rapidly growing market","Product launches into separate niches"],a:0,e:"Price rivalry transfers value directly to buyers and can be especially destructive when fixed costs and excess capacity are high."},
    {id:"str-ind-04",subject:"strategy",category:"Industry analysis",q:"Which condition most increases buyer power?",o:["A few large buyers purchase standardized products and face low switching costs","Many fragmented buyers value differentiated products","Customers are locked into a complementary ecosystem","Each buyer purchases a negligible share of output"],a:0,e:"Concentration, volume, standardization, price sensitivity, and low switching costs strengthen buyers' ability to demand concessions."},
    {id:"str-ind-05",subject:"strategy",category:"Industry analysis",q:"A supplier's input is unique, difficult to substitute, and costly to switch away from. The likely effect is...",o:["High supplier power and pressure on the focal industry's margins","Low supplier power because the input is valuable","Lower barriers to entry for the focal industry","Automatic cost leadership for buyers"],a:0,e:"Uniqueness and switching costs allow suppliers to capture more of the value through higher prices or restrictive terms."},
    {id:"str-ind-06",subject:"strategy",category:"Industry analysis",q:"What is the difference between an ex ante and an ex post entry barrier?",o:["An ex ante barrier is required before entry; an ex post barrier must be built to survive after entry","An ex ante barrier affects incumbents; an ex post barrier affects only regulators","An ex ante barrier is legal; an ex post barrier is always technological","There is no strategic difference"],a:0,e:"Licenses or capital may block entry initially, while brand, distribution, learning, and relationships may determine whether an entrant survives."},
    {id:"str-ind-07",subject:"strategy",category:"Industry analysis",q:"Why can an industry be profitable for incumbents but unattractive to entrants?",o:["Strong entry and mobility barriers protect incumbent capture but make profitable entry costly","Incumbents and entrants always face identical economics","High profits eliminate the threat of retaliation","Entrants do not consider the cost of entry"],a:0,e:"Attractiveness must account for entry cost, required capabilities, and likely incumbent response, not just observed incumbent margins."},
    {id:"str-ind-08",subject:"strategy",category:"Industry analysis",q:"Which is a substitute for a cinema rather than a direct rival within the cinema industry?",o:["A home streaming service offering the same entertainment benefit","Another cinema chain in the same city","A supplier of projection equipment","A snack concession inside the cinema"],a:0,e:"Substitutes come from outside the defined industry but satisfy a similar customer job or benefit."},
    {id:"str-ind-09",subject:"strategy",category:"Industry analysis",q:"The four largest firms have shares of 30%, 25%, 20%, and 10%. What is CR4?",o:["85%","55%","42.5%","0.85%"],a:0,e:"CR4 is the sum of the four largest market shares: 30 + 25 + 20 + 10 = 85%."},
    {id:"str-ind-10",subject:"strategy",category:"Industry analysis",q:"What is a major limitation of a static Five Forces analysis?",o:["It can understate changes in technology, regulation, channels, and industry life cycle","It cannot analyze bargaining power","It is useful only for monopolies","It always overestimates value creation"],a:0,e:"Five Forces is a structure-and-capture snapshot. Dynamic shifts can change the relevant actors, barriers, and profit logic."},

    {id:"str-dyn-01",subject:"strategy",category:"Industry dynamics & groups",q:"During industry maturity or shakeout, which pattern is most likely?",o:["Growth slows, efficiency pressure rises, and weaker firms exit","Demand uncertainty rises and standards disappear","Every entrant earns high profits","Specialist suppliers cease to exist"],a:0,e:"Maturity commonly brings slower demand growth, consolidation, cost pressure, and exit even while total sales may remain high."},
    {id:"str-dyn-02",subject:"strategy",category:"Industry dynamics & groups",q:"Which is a genuine first-mover mechanism rather than a label?",o:["Cumulative learning that lowers cost before rivals catch up","Being the oldest firm in the market","Launching first without customer adoption","Spending more than late entrants"],a:0,e:"First-mover advantage requires a mechanism such as learning, scarce-asset preemption, standards, switching costs, loyalty, or network effects."},
    {id:"str-dyn-03",subject:"strategy",category:"Industry dynamics & groups",q:"When should an analyst use a strategic group map?",o:["When firms in one industry use materially different strategies and are not equally close substitutes","Whenever an industry contains more than two firms","Only when market shares are identical","To replace all firm-level analysis"],a:0,e:"Strategic groups reveal clusters, closest rivals, mobility barriers, and segment-specific economics hidden by an industry average."},
    {id:"str-dyn-04",subject:"strategy",category:"Industry dynamics & groups",q:"Which pair makes the best axes for a strategic group map?",o:["Price tier and degree of vertical integration","Revenue and profit","Quality and customer satisfaction when they are almost perfectly correlated","Good strategy and bad strategy"],a:0,e:"Axes should represent important, variable, and reasonably independent strategic choices rather than outcomes or vague judgments."},
    {id:"str-dyn-05",subject:"strategy",category:"Industry dynamics & groups",q:"What is a mobility barrier?",o:["An obstacle that makes it costly for a firm to move from one strategic group to another","A regulation that prevents every firm from entering an industry","A temporary decline in demand","A substitute product from another industry"],a:0,e:"Brand, distribution, technology, scale, regulation, routines, and customer relationships can preserve group differences."},
    {id:"str-dyn-06",subject:"strategy",category:"Industry dynamics & groups",q:"A complementor creates strategic value when it...",o:["Raises the WTP for, or reduces adoption friction around, the focal product","Produces an identical substitute","Always lowers the focal firm's price","Eliminates the need for a business model"],a:0,e:"Complements expand value creation, though a powerful complementor can also become a bottleneck and capture a large share."},

    {id:"str-ca-01",subject:"strategy",category:"Competitive advantage",q:"Which definition best captures competitive advantage?",o:["The ability or potential to earn above-average profitability over the medium to long term","Any year in which revenue grows","Having the largest workforce","Operating in a profitable industry"],a:0,e:"Advantage is relative to rivals and must be grounded in superior value creation or capture that is at least conditionally durable."},
    {id:"str-ca-02",subject:"strategy",category:"Competitive advantage",q:"A cost advantage exists when a firm can...",o:["Offer comparable customer value at lower cost than rivals","Sell an inferior product at any low price","Reduce spending even if willingness to pay collapses","Earn high margins without a competitor comparison"],a:0,e:"Comparable value is essential. Cutting cost is not an advantage if it destroys more customer WTP than it saves."},
    {id:"str-ca-03",subject:"strategy",category:"Competitive advantage",q:"Which mechanism is a learning economy?",o:["Repeated production reduces defects and labor time per unit","Fixed costs are spread over more units","Two products share the same distribution network","A factory operates closer to full capacity"],a:0,e:"Learning improves cost or quality through accumulated experience; it differs from scale, scope, and load-factor effects."},
    {id:"str-ca-04",subject:"strategy",category:"Competitive advantage",q:"A cost leader matches rivals' prices instead of cutting price. What is the immediate capture logic?",o:["It retains the cost gap as a higher margin per unit","It automatically doubles volume","It transfers all surplus to buyers","It removes the threat of imitation"],a:0,e:"Matching price lets the firm capture its lower cost as margin. Price cutting is an alternative aimed at share and volume."},
    {id:"str-ca-05",subject:"strategy",category:"Competitive advantage",q:"Differentiation creates advantage only when...",o:["The increase in captured WTP exceeds the extra cost of being unique","The product has any unusual feature","Advertising spending exceeds competitors' spending","Every buyer values the feature equally"],a:0,e:"Uniqueness must be valuable to a target segment and translate into price, margin, volume, loyalty, or complementary sales."},
    {id:"str-ca-06",subject:"strategy",category:"Competitive advantage",q:"Which is an intangible source of differentiation?",o:["A brand associated with identity and trust","A faster processor","A lighter material","A longer warranty period"],a:0,e:"Brand, reputation, status, community, and trust are intangible. Physical performance and design features are tangible."},
    {id:"str-ca-07",subject:"strategy",category:"Competitive advantage",q:"What is causal ambiguity?",o:["Rivals cannot identify which interdependent resources and activities produce the advantage","Customers do not understand the posted price","Managers cannot calculate profit","A patent has expired"],a:0,e:"Causal ambiguity protects advantage because copying one visible feature does not reproduce the underlying system."},
    {id:"str-ca-08",subject:"strategy",category:"Competitive advantage",q:"Which action is adaptation rather than protection?",o:["Reconfiguring distribution as customers shift to a new channel","Patenting a production method","Keeping a formula secret","Creating contractual switching costs"],a:0,e:"Adaptation renews fit through regeneration or reconfiguration. Protection makes imitation or appropriation harder."},
    {id:"str-ca-09",subject:"strategy",category:"Competitive advantage",q:"Why is internal activity-system fit difficult to imitate?",o:["The value comes from many reinforcing choices rather than one isolated practice","Every activity is legally protected","The firm never needs to adapt","Competitors are unable to observe prices"],a:0,e:"A rival may copy a single activity but fail to reproduce the full configuration, trade-offs, routines, and mutual reinforcement."},
    {id:"str-ca-10",subject:"strategy",category:"Competitive advantage",q:"Which evidence best supports a claim of differentiation-based advantage?",o:["A sustained price premium, loyalty, and margins linked to valued uniqueness","A long list of product features with no customer response","High revenue in a booming industry","A management statement that the brand is premium"],a:0,e:"Evidence should show that a specific uniqueness raises WTP and that the firm captures enough of it after the associated costs."},

    {id:"str-scope-01",subject:"strategy",category:"Growth, boundaries & scope",q:"Vertical integration means...",o:["Owning or controlling multiple stages of a value chain","Selling the same product in more countries","Adding an unrelated product category","Using more than one supplier"],a:0,e:"Backward integration moves toward inputs; forward integration moves toward channels and customers."},
    {id:"str-scope-02",subject:"strategy",category:"Growth, boundaries & scope",q:"At what level should a make-or-buy decision normally be analyzed?",o:["The specific transaction or activity interface","The firm's entire identity","The industry's average ROE","The CEO's preferred governance style"],a:0,e:"Different activities have different uncertainty, coordination, specificity, and scale economics, so selective boundaries are usually superior."},
    {id:"str-scope-03",subject:"strategy",category:"Growth, boundaries & scope",q:"High asset specificity strengthens the case for integration because it...",o:["Creates dependency and exposes the investing party to hold-up","Guarantees external scale economies","Makes contracts complete","Removes the need for coordination"],a:0,e:"Transaction-specific investments lose value outside the relationship, increasing opportunism and renegotiation risk."},
    {id:"str-scope-04",subject:"strategy",category:"Growth, boundaries & scope",q:"When is outsourcing generally more attractive?",o:["The activity is standardized and competitive specialists have superior scale and learning","Quality is impossible to specify and adaptation is continuous","A scarce resource is strategically core","Partner hold-up risk is severe"],a:0,e:"Markets provide flexibility and external scale when the interface is stable, specifiable, and served by capable suppliers."},
    {id:"str-scope-05",subject:"strategy",category:"Growth, boundaries & scope",q:"What type of diversification operates in multiple markets linked by shared resources or capabilities?",o:["Related diversification","Unrelated diversification","Backward integration","Geographic concentration"],a:0,e:"Related diversification has a meaningful common thread such as brand, technology, distribution, operations, or customers."},
    {id:"str-scope-06",subject:"strategy",category:"Growth, boundaries & scope",q:"What are Porter's three tests for value-creating diversification?",o:["Attractiveness, cost of entry, and better-off","Growth, market share, and revenue","Scale, scope, and learning","Price, cost, and quantity"],a:0,e:"The target must be attractive, entry must not consume all surplus, and common ownership must make the businesses worth more together."},
    {id:"str-scope-07",subject:"strategy",category:"Growth, boundaries & scope",q:"Why is risk spreading usually a weak justification for corporate diversification?",o:["Shareholders can generally diversify their portfolios more cheaply","Diversification always increases risk","Corporate parents cannot allocate capital","Related businesses never share risk"],a:0,e:"Corporate scope should create operating or parenting value that investors cannot replicate through simple portfolio diversification."},
    {id:"str-scope-08",subject:"strategy",category:"Growth, boundaries & scope",q:"What is parenting advantage?",o:["Headquarters adds more value through governance, resources, and coordination than alternative owners could","A parent company owns more than 50% of a subsidiary","The largest business subsidizes every smaller business","Managers prefer a larger corporate portfolio"],a:0,e:"The relevant comparison is whether this particular corporate parent is the best available owner, not merely whether ownership is possible."},
    {id:"str-scope-09",subject:"strategy",category:"Growth, boundaries & scope",q:"Which mode offers faster access and greater control than internal development or an alliance, but often at a high entry price?",o:["Acquisition","Licensing","Organic growth","Franchising"],a:0,e:"Acquisition buys an existing brand, customers, capabilities, and control, but integration and overpayment risks can destroy value."},
    {id:"str-scope-10",subject:"strategy",category:"Growth, boundaries & scope",q:"Which is a common cost of excessive diversification?",o:["Managerial attention is dispersed and coordination complexity rises","Every business gains stronger focus","Synergies become automatic","The cost of entry falls to zero"],a:0,e:"Complexity, weak fit, slow adaptation, cannibalization, and unrealized synergies can outweigh scope economies."},

    {id:"str-esg-01",subject:"strategy",category:"Sustainability & stakeholders",q:"Which statement best distinguishes ESG from CSR?",o:["ESG is an investor-oriented risk/metric lens; CSR concerns voluntary responsibilities beyond compliance","ESG concerns only emissions; CSR concerns only employees","ESG and CSR are exact synonyms","CSR is mandatory financial reporting"],a:0,e:"Sustainability, ESG, and CSR overlap but serve different analytical purposes and should not be treated as interchangeable labels."},
    {id:"str-esg-02",subject:"strategy",category:"Sustainability & stakeholders",q:"What is shared value?",o:["Practices that improve company competitiveness while advancing social or economic conditions","Any charitable donation","Redistributing all firm surplus to stakeholders","Maximizing an ESG score regardless of business impact"],a:0,e:"Shared value expands the value created by linking a stakeholder benefit to products, value-chain productivity, or local clusters."},
    {id:"str-esg-03",subject:"strategy",category:"Sustainability & stakeholders",q:"A stakeholder has high power but opposes a proposed initiative. What is the most appropriate default response?",o:["Negotiate, redesign, neutralize, or contain the conflict","Ignore the stakeholder","Use the stakeholder only for symbolic legitimacy","Treat the stakeholder as automatically aligned"],a:0,e:"The power-alignment matrix prioritizes active engagement with powerful opponents because they can materially alter the outcome."},
    {id:"str-esg-04",subject:"strategy",category:"Sustainability & stakeholders",q:"Why can a high ESG rating be insufficient evidence of strong sustainability strategy?",o:["Ratings may diverge in scope and measurement, and a score may not show material outcomes or value logic","All ESG data is fraudulent","Only profit measures sustainability","Ratings cannot include governance"],a:0,e:"Metrics are evidence, not the conclusion. Materiality, outcomes, trade-offs, and causal effects on WTP, cost, risk, or license matter."},
    {id:"str-esg-05",subject:"strategy",category:"Sustainability & stakeholders",q:"Which initiative most clearly redefines productivity in the value chain?",o:["Reducing energy and material waste in a way that lowers cost and environmental impact","Making an unrelated donation","Publishing a slogan without operational change","Increasing packaging while advertising sustainability"],a:0,e:"Shared-value productivity initiatives improve both company economics and a social or environmental outcome."},

    {id:"str-crocs-01",subject:"strategy",category:"Crocs exam application",q:"What type of diversification did Crocs pursue by acquiring HEYDUDE?",o:["Related horizontal diversification","Unrelated conglomerate diversification","Backward vertical integration","Forward vertical integration"],a:0,e:"Both brands compete in casual footwear and can potentially share manufacturing, digital, wholesale, and brand-building capabilities."},
    {id:"str-crocs-02",subject:"strategy",category:"Crocs exam application",q:"Which was the strongest strategic reason for using an acquisition to enter HEYDUDE's segment?",o:["Fast access to an existing brand, products, customers, and distribution with full control","Eliminating all integration risk","Avoiding the need to pay an entry price","Ensuring that the two brands could never cannibalize each other"],a:0,e:"Acquisition accelerates access and gives more control than an alliance, although purchase price and integration risks remain."},
    {id:"str-crocs-03",subject:"strategy",category:"Crocs exam application",q:"Which fact most directly signals cultural distance in Crocs' China expansion?",o:["Brand discovery relies heavily on Douyin, Xiaohongshu, WeChat, and locally relevant celebrities","China is geographically far from Colorado","Chinese footwear spending per capita is lower","Data-localization rules apply"],a:0,e:"Media, celebrity, design, and consumption norms are cultural. Crocs responded with Chinese ambassadors and local designers."},
    {id:"str-crocs-04",subject:"strategy",category:"Crocs exam application",q:"Which Crocs China challenge belongs primarily to administrative distance in CAGE?",o:["Advertising rules, e-commerce licensing, data localization, and trade tensions","Different consumer discovery habits","Lower per-capita footwear spending","Physical distance from the United States"],a:0,e:"Administrative distance reflects legal, regulatory, political, and institutional differences between countries."},
    {id:"str-crocs-05",subject:"strategy",category:"Crocs exam application",q:"Crocs' primary competitive advantage is best classified as...",o:["Differentiation based on recognizable design, material features, brand, and personalization","Cost leadership based on the lowest market price","A protected monopoly over all casual footwear","Unrelated diversification"],a:0,e:"Croslite, the polarizing design, collaborations, and Jibbitz raise WTP and distinguish Crocs from broader footwear rivals."},
    {id:"str-crocs-06",subject:"strategy",category:"Crocs exam application",q:"The Jibbitz charm system is strategically important because it...",o:["Acts as a complement that raises personalization, repeat purchases, and willingness to pay","Is an unrelated business with no link to footwear","Replaces the need for brand marketing","Creates cost leadership through lower resin prices"],a:0,e:"The complement turns a standardized shoe into a platform for identity and recurring accessory purchases."},
    {id:"str-crocs-07",subject:"strategy",category:"Crocs exam application",q:"Why did Crocs close its factories and outsource production?",o:["To gain flexibility and focus internal resources on core brand and design activities","To increase asset specificity with one supplier","To improve control by owning more stages","To enter footwear manufacturing for the first time"],a:0,e:"Outsourcing standardized manufacturing can exploit specialist scale while Crocs concentrates on differentiation and demand creation."},
    {id:"str-crocs-08",subject:"strategy",category:"Crocs exam application",q:"A consolidation wave among footwear retailers would most likely...",o:["Reduce industry attractiveness by increasing distributor bargaining power","Increase attractiveness by eliminating buyer power","Leave profitability unchanged because only consumers matter","Remove the threat of substitutes"],a:0,e:"Fewer, larger wholesale customers can demand better prices and terms, compressing footwear brands' margins."},
    {id:"str-crocs-09",subject:"strategy",category:"Crocs exam application",q:"Which Crocs action best exemplifies defending advantage through adaptation?",o:["Launching culturally relevant artist and designer collaborations as tastes evolve","Relying only on the original 2002 design","Keeping all marketing unchanged","Using a patent without product or brand renewal"],a:0,e:"Collaborations regenerate cultural relevance and help the brand continue to fit changing customer preferences."},
    {id:"str-crocs-10",subject:"strategy",category:"Crocs exam application",q:"The $737 million HEYDUDE goodwill impairment most strongly suggests that...",o:["Expected acquisition synergies and future cash flows were materially overestimated","HEYDUDE had become a cost leader","Crocs had paid no acquisition premium","The acquisition automatically passed the better-off test"],a:0,e:"The impairment, falling revenue, and wholesale reset indicate that the original valuation and integration thesis did not fully materialize."},
    {id:"str-crocs-11",subject:"strategy",category:"Crocs exam application",q:"Which Porter National Diamond factor is illustrated by intense US rivalry from Nike, Skechers, and challenger brands?",o:["Firm strategy, structure, and rivalry","Factor conditions","Demand conditions","Related and supporting industries"],a:0,e:"Domestic rivalry pressures firms to innovate and differentiate before competing internationally."},
    {id:"str-crocs-12",subject:"strategy",category:"Crocs exam application",q:"Which Porter National Diamond factor is illustrated by high US footwear spending and trend-sensitive consumers?",o:["Demand conditions","Factor conditions","Related and supporting industries","Government ownership"],a:0,e:"Sophisticated and demanding home customers can push a company to develop stronger products and marketing capabilities."}
  ];

  // Distribute the correct choice across A-D while preserving the underlying answer.
  questions.forEach((item, index) => {
    const shift = index % item.o.length;
    item.o = item.o.slice(shift).concat(item.o.slice(0, shift));
    item.a = (item.a - shift + item.o.length) % item.o.length;
  });
  window.QUESTION_BANK.push(...questions);
})();
